# Generated by Django 4.2.30 on 2026-07-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr_officer', 'HR Officer'), ('department_head', 'Department Head'), ('employee', 'Employee'), ('applicant', 'Job Applicant'), ('graduate_trainee', 'Graduate Trainee'), ('intern', 'Student Intern'), ('admin', 'System Administrator')], default='employee', max_length=30),
        ),
    ]
