# Generated by Django 4.2.30 on 2026-07-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='title',
        ),
    ]
