# Generated by Django 4.2.30 on 2026-07-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, unique=True),
        ),
    ]
