# Generated by Django 4.2.30 on 2026-07-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_department_parent_remove_grade_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='supervisor',
        ),
    ]
