# Generated by Django 4.2.30 on 2026-07-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leaverequest_current_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['name']},
        ),
    ]
