# Generated by Django 4.2.30 on 2026-07-15 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_type', models.CharField(choices=[('graduate', 'Graduate Trainee'), ('intern', 'Student Intern')], max_length=20)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('course', models.CharField(blank=True, max_length=200)),
                ('registration_no', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('extended', 'Extended')], default='active', max_length=20)),
                ('stipend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accommodation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.department')),
            ],
            options={
                'db_table': 'trainees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('graduate', 'Graduate Trainee'), ('internship', 'Student Internship')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('completed', 'Completed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_programs', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='employees.department')),
            ],
            options={
                'db_table': 'training_programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraineeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='trainees.trainee')),
            ],
            options={
                'db_table': 'trainee_courses',
            },
        ),
        migrations.CreateModel(
            name='TraineeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('midterm', 'Mid-Term'), ('final', 'Final')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Satisfactory'), ('D', 'Poor')], max_length=1)),
                ('comments', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='trainees.trainee')),
            ],
            options={
                'db_table': 'trainee_assessments',
                'ordering': ['assessed_at'],
            },
        ),
        migrations.AddField(
            model_name='trainee',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='trainees.trainingprogram'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_trainees', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
