# Generated by Django 4.2.30 on 2026-07-15 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('financial_year', models.CharField(max_length=10)),
                ('current_staff', models.PositiveIntegerField(default=0)),
                ('required_staff', models.PositiveIntegerField(default=0)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_manpower_plans', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower_plans', to='employees.department')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manpower_plans',
                'ordering': ['-created_at'],
                'unique_together': {('department', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='EstablishmentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_count', models.PositiveIntegerField(default=1)),
                ('filled_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('filled', 'Filled'), ('vacant', 'Vacant'), ('frozen', 'Frozen')], default='vacant', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.grade')),
                ('manpower_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='manpower.manpowerplan')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position')),
            ],
            options={
                'db_table': 'establishment_posts',
            },
        ),
    ]
