# Generated by Django 4.2.30 on 2026-07-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_transfer_from_branch_transfer_to_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='is_hr_record',
            field=models.BooleanField(default=False),
        ),
    ]
